### PR TITLE
added mysql backed queue along with the test

### PR DESCRIPTION
**Pull request by harshals**
added mysql backend for the queue along with the test.

### CODE REVIEW

**Comment by jamadam** [comment]
Wow! Thanks!

I made a list of tasks to do before I can merge the PR.
- Update travis.yml to make it pass the tests.
- Keep mysql optional dependancy.
- Make the tests skkipable in case mysql is not found.
- Make sure the module has an advantage in "broad crawling" over existing one.

It will take some time to get them done so any help or advices would be appriciated.

**Comment by harshals** [comment]
great...will keep you posted on the updates..

Harshal Shah

**Comment by jamadam** [comment]
Tests passed on Travis CI for now :)

https://github.com/harshals/WWW-Crawler-Mojo/compare/master...jamadam:harshals-mysql-queue

**Comment by harshals** [comment]
On Tue, Oct 20, 2015 at 3:57 PM, jamadam notifications@github.com wrote:

> on Travis CI for now :)
> 
> thanks. ..have minor changes to make mysql operations more atomic.  btw how
> do you run the bot in parallel ?

Harshal Shah

**Comment by jamadam** [comment]
Ah, I haven't thought of parallel processing. That seems to be a sensible reason to adopt RDBMS as well as achieving ability of broad crawling. I haven't got any idea on the interface design for parallel crawling, though.

**Comment by jamadam** [comment]
I changed the test scheme. Setting DB connection info via $ENV may be better (refered to minion, Mojo::Pg, Mojo::mysql etc).

0c80b7543f9f2af238d6c7c92e232110722fa891

TODOs
- Look into the actual code.
- Consider the way of parallel crawling
- Write document.
- Example code.

**Comment by jamadam** [comment]
While the TODOs are undone, I merged the commit into master and ready to ship it as experimental feature. When all TODOs get completed, I would remove the EXPERIMENTAL mark. Any further contribution is appreciated.

And this time I learned the importance of coding rules for collaboration. Please try the .perltidyrc I ported from mojolicious project.

```
find lib/ -name '*.pm' -print -exec perltidy -pro=.perltidyrc -nst -b -bext='/' {} \;
find t/ -name '*.t' -print -exec perltidy -pro=.perltidyrc -nst -b -bext='/' {} \;
```

**Comment by harshals** [comment]
On Thu, Oct 22, 2015 at 4:32 PM, jamadam notifications@github.com wrote:

> learned the importance of coding rules for collaboration. Please try the

sure ..will do that..

Harshal Shah

**Pull request merged**
